services:
  nginx:
    build: .
    ports:
      - "80:80"

  backend:
    build: ./hello_service
    ports:
      - "8000:8000"
    command: uvicorn hello:app --host 0.0.0.0 --port 8000

  world_service:
    build: ./world_service
    ports:
      - "8001:8001"
    command: uvicorn world:app --host 0.0.0.0 --port 8001

  locations:
    build: ./locations
    ports:
      - "9000:9000"
    command: uvicorn locations:app --host 0.0.0.0 --port 9000